name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Smoke dataset
      run: |
        python scripts/create_dummy_dataset.py
        python scripts/prepare_split.py --labels data/labels.csv --val-size 0.2
    - name: Train 1 epoch (CPU)
      run: |
        python -m src.train --train-csv data/splits/train.csv --val-csv data/splits/val.csv --epochs 1 --batch-size 8 --out checkpoints/resnet18_multitask.pt
    - name: Predict one
      run: |
        python -m src.predict --ckpt checkpoints/resnet18_multitask.pt --image data/raw/dummy_000.png
